### ISSUE TITLE
【依頼】Proeospace挙動確認

### ISSUE THREAD

**Issue by Miyuki-Hara** [yuki-hatsuharu/protospace-37726#1]
https://protospace-37726.herokuapp.com/

**Comment by shodai-ito** [comment]
@yuki-hatsuharu さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**`ユーザー詳細機能`**
- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
トップページ及びユーザー詳細ページのプロトタイプ投稿者名をクリックしても、ユーザー詳細ページに遷移できません。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Miyuki-Hara** [comment]
ご指摘ありがとうございます。
すぐに修正いたします。

**Comment by Miyuki-Hara** [comment]
修正いたしました。
お手数をお掛けいたしますが、再度、下記URLにて挙動の確認をお願い申し上げます。

https://protospace-37726.herokuapp.com/

**Comment by snkw-works** [comment]
@yuki-hatsuharu さん、修正とご提出ありがとうございます‼︎
正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
